{
  "project_name": "live",
  "message": "",
  "id": "1972208801",
  "culprit": "__main__ in <module>",
  "project_slug": "foo-live",
  "url": "https://sentry.io/organizations/bar-foundation/issues/1972208801/?referrer=webhooks_plugin",
  "level": "error",
  "triggering_rules": [
    "Send a notification for new events"
  ],
  "event": {
    "extra": {
      "sys.argv": [
        "data/trigger-exception.py"
      ]
    },
    "_ref_version": 2,
    "_ref": 218288,
    "id": "c916dccfd58e41dcabaebef0091f0736",
    "_metrics": {
      "bytes.ingested.event": 2229,
      "bytes.stored.event": 3021
    },
    "culprit": "__main__ in <module>",
    "title": "ValueError: new sentry error.",
    "event_id": "c916dccfd58e41dcabaebef0091f0736",
    "grouping_config": {
      "enhancements": "eJybzDhxY05qemJypZWRgaGlroGxrqHRBABbEwcC",
      "id": "legacy:2019-03-12"
    },
    "platform": "python",
    "version": "7",
    "location": "trigger-exception.py",
    "logger": "",
    "type": "error",
    "metadata": {
      "function": "<module>",
      "type": "ValueError",
      "value": "new sentry error.",
      "filename": "trigger-exception.py"
    },
    "tags": [
      [
        "level",
        "error"
      ],
      [
        "runtime",
        "CPython 3.8.5"
      ],
      [
        "runtime.name",
        "CPython"
      ],
      [
        "server_name",
        "enterprise"
      ]
    ],
    "timestamp": 1603322711.147672,
    "fingerprint": [
      "{{ default }}"
    ],
    "hashes": [
      "05eeb8cc2a9103790797a56728cfa1e8"
    ],
    "sdk": {
      "version": "0.19.1",
      "name": "sentry.python",
      "packages": [
        {
          "version": "0.19.1",
          "name": "pypi:sentry-sdk"
        }
      ],
      "integrations": [
        "argv",
        "atexit",
        "dedupe",
        "excepthook",
        "logging",
        "modules",
        "stdlib",
        "threading"
      ]
    },
    "received": 1603322712.317751,
    "exception": {
      "values": [
        {
          "stacktrace": {
            "frames": [
              {
                "function": "<module>",
                "abs_path": "/home/user/software/bar/bar-foo/data/trigger-exception.py",
                "pre_context": [
                  "",
                  "",
                  "if __name__ == \"__main__\":",
                  "    sentry_sdk.init(dsn=DSN_SECRET)",
                  "    try:"
                ],
                "post_context": [
                  "    except Exception as e:",
                  "        sentry_sdk.capture_exception(e)"
                ],
                "vars": {
                  "__spec__": "None",
                  "__builtins__": "<module 'builtins' (built-in)>",
                  "__annotations__": null,
                  "__file__": "'data/trigger-exception.py'",
                  "__loader__": "<_frozen_importlib_external.SourceFileLoader object at 0x7f80a18acc70>",
                  "__cached__": "None",
                  "__name__": "'__main__'",
                  "__package__": "None",
                  "__doc__": "None",
                  "sentry_sdk": "<module 'sentry_sdk' from '/home/user/.virtualenvs/sentry-test/lib/python3.8/site-packages/sentry_sdk/__init__.py'>"
                },
                "module": "__main__",
                "filename": "trigger-exception.py",
                "lineno": 10,
                "in_app": false,
                "data": {
                  "orig_in_app": 1
                },
                "context_line": "        raise ValueError(\"new sentry error.\")"
              }
            ]
          },
          "type": "ValueError",
          "value": "new sentry error."
        }
      ]
    },
    "_meta": {
      "exception": {
        "values": {
          "0": {
            "stacktrace": {
              "frames": {
                "0": {
                  "vars": {
                    "": {
                      "len": 12
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "level": "error",
    "contexts": {
      "runtime": {
        "version": "3.8.5",
        "type": "runtime",
        "name": "CPython",
        "build": "3.8.5 (default, Jul 28 2020, 12:59:40) \n[GCC 9.3.0]"
      }
    },
    "modules": {
      "six": "1.14.0",
      "packaging": "20.3",
      "pip": "20.0.2",
      "pyparsing": "2.4.6",
      "html5lib": "1.0.1",
      "appdirs": "1.4.3",
      "distlib": "0.3.0",
      "msgpack": "0.6.2",
      "sentry-sdk": "0.19.1",
      "pytoml": "0.1.21",
      "ipaddr": "2.2.0",
      "webencodings": "0.5.1",
      "progress": "1.5",
      "certifi": "2019.11.28",
      "distro": "1.4.0",
      "wheel": "0.34.2",
      "pkg-resources": "0.0.0",
      "urllib3": "1.25.8",
      "retrying": "1.3.3",
      "colorama": "0.4.3",
      "cachecontrol": "0.12.6",
      "lockfile": "0.12.2",
      "pep517": "0.8.2",
      "contextlib2": "0.6.0",
      "chardet": "3.0.4",
      "setuptools": "44.0.0",
      "requests": "2.22.0",
      "idna": "2.8"
    },
    "project": 218288,
    "key_id": "430951"
  },
  "project": "foo-live",
  "logger": null
}
